version: '3'

services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - "./web:/var/www/html"
        ports:
            - "8000:8080"
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql
        env_file:
        - .env
        ports:
        - '3307:3306'
        volumes:
        - data-volume:/var/lib/mysql
volumes:
  data-volume:
    driver: local
